### ISSUE TITLE
Frozen on open (not related to gtk3 patch)

### ISSUE THREAD

**Issue by quequotion** [nekohayo/pavumeter#1]
For a while pavumeter has not ben working, neither Lennart's original, nor--as I discovered today--this one.

I don't know if Lennart is still maintaining his program, nor how to tell him it is broken.

As soon as the application opens, it is frozen. If audio is playing, levels will be shown where they were at the moment the application opened until it is (forcibly) closed. If audio is not playing, levels never show (because the application is frozen with levels at zero).

I know it's been a long time, and it's not the objective of this fork.

Is this something you can help with?

I can take a few stabs in the dark myself, but I don't have a clue where to start.

**Comment by nekohayo** [comment]
Is pavucontrol affected in the same way? Maybe your issue has something to do with the replacement of PulseAudio by PipeWire? I'm not able to provide support as I have no clue how this all works, but if this is related to PipeWire you may want to file it [in pipewire](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues?scope=all&state=opened&search=pavumeter) or [pavucontrol issues](https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/issues/) (didn't find the pavumeter equivalent issue tracker)

**Comment by quequotion** [comment]
I never made the switch to pipewire. I am still using pulseaudio, version 15.

Not sure how long exactly this has been going on, but since before people began to regard pipewire as having deprecated pulseaudio.

It's probably either become incompatible with changes to pulseaudio or changes to GTK, but I lean toward the issue being with the toolkit.

**Comment by D33M0N** [comment]
unfunny sidenote, Manjaro XFCE Volume control volume bars stopped working also, but much later than pavumeter ones.
Now I have no visual indication of volumes at all :-(
eff pipewire. (I don't use it, but it's installed into the system by Manjaro team by default since forever... no idea why or how it's integrated and/or supposed to work with pulse... and it's actually working also it seems... I have task /usr/bin/pipewire running.)

**Comment by quequotion** [comment]
It has come to my attention that, at least in my case, this issue is particular to using the [a52 AC3 surround-sound plugin](https://github.com/alsa-project/alsa-plugins/issues/42).

pavumeter works normally if I switch to stereo mode.

This is most likely not a bug in pavumeter.
